/**
 * Copyright (c) 2015-present, Facebook, Inc.
 * All rights reserved.
 *
 * This source code is licensed under the BSD-style license found in the
 * LICENSE file in the root directory of this source tree. An additional grant
 * of patent rights can be found in the PATENTS file in the same directory.
 */

#import "AppDelegate.h"
#import "MyClass.h"
#import "RCTRootView.h"

@implementation AppDelegate

- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
  NSURL *jsCodeLocation;

  /**
   * Loading JavaScript code - uncomment the one you want.
   *
   * OPTION 1
   * Load from development server. Start the server from the repository root:
   *
   * $ npm start
   *
   * To run on device, change `localhost` to the IP address of your computer
   * (you can get this by typing `ifconfig` into the terminal and selecting the
   * `inet` value under `en0:`) and make sure your computer and iOS device are
   * on the same Wi-Fi network.
   */
  //进入工程目录运行react-native bundle --entry-file app/components/main.js --bundle-output ./iOS/bundle/main.jsbundle --platform ios --assets-dest ./iOS/bundle --dev false
  
  NSString *jsBundlePath = [NSSearchPathForDirectoriesInDomains(NSDocumentDirectory, NSUserDomainMask, YES) objectAtIndex:0];
  jsBundlePath = [jsBundlePath stringByAppendingPathComponent:@"JSBundle"];
  if(![[NSFileManager defaultManager] fileExistsAtPath:jsBundlePath])
  {
    [[NSFileManager defaultManager] createDirectoryAtPath:jsBundlePath withIntermediateDirectories:NO attributes:nil error:nil];
  }
  
  NSString *path = [[NSBundle mainBundle] pathForResource:@"Settings" ofType:@"bundle"];
  NSString *ip = nil;
  if(path)
  {
    NSDictionary  *settings = [NSDictionary dictionaryWithContentsOfFile:[path stringByAppendingPathComponent:@"Root.plist"]];
    NSArray *preferences = [settings objectForKey:@"PreferenceSpecifiers"];
    NSMutableDictionary *defaults = [[NSMutableDictionary alloc] initWithCapacity:[preferences count]];
    for(NSDictionary *dic in preferences)
    {
      NSString *key = [dic objectForKey:@"Key"];
      if(key)
      {
        [defaults setObject:[dic objectForKey:@"DefaultValue"] forKey:key];
      }
    }
    [[NSUserDefaults standardUserDefaults] registerDefaults:defaults];
  }
  if(!ip)
  {
    NSUserDefaults *defaults = [NSUserDefaults standardUserDefaults];
    ip = [defaults stringForKey:@"ip_preference"];
    if(!ip||ip.length==0||[ip isEqualToString:@"52.77.199.26"]||[ip isEqualToString:@"54.222.159.156"])
    {
      if([[NSFileManager defaultManager] fileExistsAtPath:[jsBundlePath stringByAppendingPathComponent:@"main.jsbundle"]])
      {
        jsCodeLocation = [NSURL fileURLWithPath:[jsBundlePath stringByAppendingPathComponent:@"main.jsbundle"]];
      }
      else
      {
        jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
      }
      
    }
    else
    {
        jsCodeLocation = [[NSBundle mainBundle] URLForResource:@"main" withExtension:@"jsbundle"];
      //jsCodeLocation = [NSURL URLWithString:[NSString stringWithFormat:@"http://%@:8081/index.ios.bundle?platform=ios&dev=true",ip]];
    }
  }
  /**
   * OPTION 2
   * Load from pre-bundled file on disk. The static bundle is automatically
   * generated by "Bundle React Native code and images" build step.
   */
  
    NSLog(@"%@",jsCodeLocation);
  RCTRootView *rootView = [[RCTRootView alloc] initWithBundleURL:jsCodeLocation
                                                      moduleName:@"ReactNativeRocketChat"
                                               initialProperties:nil
                                                   launchOptions:launchOptions];

  self.window = [[UIWindow alloc] initWithFrame:[UIScreen mainScreen].bounds];
  UIViewController *rootViewController = [UIViewController new];
  rootViewController.navigationController.interactivePopGestureRecognizer.enabled = NO;
  rootViewController.view = rootView;
  self.window.rootViewController = rootViewController;
  [self.window makeKeyAndVisible];
  return YES;
}
#if __IPHONE_OS_VERSION_MAX_ALLOWED >= 90000
- (BOOL)application:(UIApplication *)application continueUserActivity:(NSUserActivity *)userActivity restorationHandler:(void (^)(NSArray *))restorationHandler{
  
  //RCTRootView *rootView = (RCTRootView*)self.window.rootViewController.view;
  NSString *identifier = [userActivity.userInfo objectForKey:@"kCSSearchableItemActivityIdentifier"];
  NSString *appId = [[NSBundle mainBundle] bundleIdentifier];
  if([identifier hasPrefix:appId])
  {
    identifier = [identifier stringByReplacingOccurrencesOfString:appId withString:@""];
  }
  //[rootView.bridge.eventDispatcher sendAppEventWithName:@"pasteBoard" body:@{@"value":aString}];
  MyClass *my = [[MyClass alloc] init];
  [my sendOpen:[[identifier componentsSeparatedByString:@"_"] objectAtIndex:0]];
  return YES;
  
}
#endif
@end
